apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sentiment-api
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: sentiment-api  # select the Service by label
  namespaceSelector:
    matchNames:
      - default         # namespace where Service lives
  endpoints:
    - port: http          # name of the Service port
      path: /actuator/prometheus
      interval: 5s
